// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $create_contact from "./routes/create-contact.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $ChatBox from "./islands/ChatBox.tsx";
import * as $ContactList from "./islands/ContactList.tsx";
import * as $CreateContactForm from "./islands/CreateContactForm.tsx";
import * as $MessengerApp from "./islands/MessengerApp.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/create-contact.tsx": $create_contact,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ChatBox.tsx": $ChatBox,
    "./islands/ContactList.tsx": $ContactList,
    "./islands/CreateContactForm.tsx": $CreateContactForm,
    "./islands/MessengerApp.tsx": $MessengerApp,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
